### ISSUE TITLE
Program description when there is podcast info

### ISSUE THREAD

**Issue by beaulalume** [iago1460/django-radio#10]
When you open the Schedule and click on a program, a description appears. But when the program shows the info of the last podcast, the description almost disappear (for example, on Cuac FM's Recendo). It would be nice to have the whole description, or being able to click on the ellipsis to open the whole description.

**Comment by iago1460** [comment]
This shouldn't be a problem with the new template (see v2)

**Comment by beaulalume** [comment]
Now, on v2.1, if you click on broadcast you can see everything: description, podcasts, members... Just great! Also when you click on live programs to be on 36h (more or less).

But if you click on live programs that where released before current time, you only see the last podcast and the members. No description or other podcasts.

And if you click on live programs that will be released in the next 36h (more or less), it shows "none podcast, it will be available in 1 day, X hours). You also can see the members. But no description or other podcasts.
