### ISSUE TITLE
Scroll time configuration not working

### ISSUE THREAD

**Issue by AlexCortinas** [iago1460/django-radio#13]
If I have understood properly its function (set the starting time of the schedule visualization), the option "Scroll time" is not working properly. It can be set in "Administration" > "Global Settings" > "Calendar Configuration".

**Comment by AlexCortinas** [comment]
According to fullcalendar docs, if *height* and *contentHeight* are set to 'auto', the calendar always takes the required height in order to not have a scroll bar, so no scroll down takes place and then *scrollTime* parameter is not used at all. I can think in these possible solutions:

* Removing the *scrollTime* parameter. Then the calendar starts always at *minTime* and it has no scroll bar.
* Adding, at least, the parameter *height* and maybe the parameter *contentHeight*, used both of them in fullcalendar, in the schedule configuration view. This way the admin decides wheter to have a fixed height and a scroll bar or not.

**Comment by iago1460** [comment]
Thanks for given detailed information, I decided to remove this setting from the config.
I have added a new setting [slot duration](https://fullcalendar.io/docs/agenda/slotDuration/) which I think is more valuable
