### ISSUE TITLE
Problems with Google fonts with RadioCo under https

### ISSUE THREAD

**Issue by txenoo** [iago1460/django-radio#15]
Actually RadioCo refers to several fonts URLs using http, but it should be agnostic to the repository to avoid having warning when radioco is under https beacause browsers block resources not under https in https connections.

The solution whould be change:

http://fonts.googleapis.com/css?family=Raleway:400,700,900

For 

//fonts.googleapis.com/css?family=Raleway:400,700,900

**Comment by iago1460** [comment]
Yes, you are totally right. Thanks for the pull request.
