### ISSUE TITLE
Last episodes default name should be Program Name - Episode insted of None

### ISSUE THREAD

**Issue by txenoo** [iago1460/django-radio#17]
Last release of RadioCo has available in the home page the list of the last radio-shows published. One of the problems is that the default name of the episodes is None until the show manager edits the episode information. So the usual webpage last episodes is None None None :)

**Comment by iago1460** [comment]
Fixed

**Comment by txenoo** [comment]
There is a problem with current implementation, as after upgrading the result is still NONE
