### ISSUE TITLE
Support markup language in text fields

### ISSUE THREAD

**Issue by txenoo** [iago1460/django-radio#3]
There has been a request from the users about the possibility to include some markup in the description fields available in radioco to include links to images, and enable lists and other different formats available in websites.

It would be useful to support some kind of markup language as could be Markdown. There is some information about how to use Markup in Django Project webpage.
https://code.djangoproject.com/wiki/UsingMarkup

If possible it would be nice some kind of WYSIWYG editor to make easy the use of formating options for non technical users. Here is a list of possible editors here https://www.djangopackages.com/grids/g/wysiwyg/

**Comment by iago1460** [comment]
A WYSIWYG was added to the project ([release notes](http://django-radio.readthedocs.org/en/latest/upgrade/1.1.1.html))
