### ISSUE TITLE
Publicar los podcast en una url, con un formato gson o similar para una app móvil

### ISSUE THREAD

**Issue by pablogrela** [iago1460/django-radio#39]
Estoy interesado en que la aplicación radioco publicase en una url los podcast para que pueden ser cogidos por una aplicación móvil android:
https://github.com/pablogrela/radiocom-android
Con el siguiente estilo:
"data":[{"_id":"57c801c620c6079304a2dda9","description":"El programa de series en serio","logo_url":"http://image","rss_url":"http://podcastrss","title":"Spoiler"},{"_id":"57c8039b20c6079304a2ddc2","description":"Irmans","logo_url":"http://image","rss_url":"http://podcastrss","title":"Alegría","appId":"radiocom"}].
La idea es integrarlo varias funcionalidades de cuacfm en la aplicación móvil.
@txenoo 
@iago1460 
@ficiverson

**Comment by iago1460** [comment]
Cierro esta petición según lo hablado por email.
Lo tendré en cuenta cuando libere la siguiente version en caso de que no hayas podido añadirlo tu mismo.
