### ISSUE TITLE
Improvement idea for "ending date"

### ISSUE THREAD

**Issue by beaulalume** [iago1460/django-radio#43]
Sometimes people puts an ending date unintentionally. Would it be possible to put a warning message? Something like "Are you sure? From this date on the program won´t appear on the schedule and podcasts won´t be recorded".

**Comment by iago1460** [comment]
Only admin users should have access to this page. Probably a new permission to enable advance settings would be a better approach if we want to allow its staff to edit its description.

**Comment by iago1460** [comment]
I have decided to hide the end and start date fields if the user doesn't have the programmes.add_programme permission.

This will be available in the next release. 
Regards.
