### ISSUE TITLE
Possibility to change the available roles in Radioco

### ISSUE THREAD

**Issue by txenoo** [iago1460/django-radio#5]
Nowadays in Radioco there are 4 roles as people can participate in programs. Presenter, Informer and Contributor. Nowadays in the radio we are deploying the software the principal roles are "Presenter" and "Technician". 

It would be good idea the possibility to change easy the roles without edditing radio/apps/programmes/models.py

Is there a better option ?

**Comment by iago1460** [comment]
Right now it is no possible without editing the code.

My attempt was to create a generic list of all the roles of a radio allowing translations out of box but I will change to a simple CharField in next versions.

**Comment by iago1460** [comment]
Completed in [version 3.2](http://django-radio.readthedocs.io/en/latest/upgrade/3.1.html)
